##############################################################################
# dynamodb.tf — DynamoDB tables for poll data, deduplication, and audit log.
#
# Compliance notes:
#   - SOC2:  AuditLog table captures every state change with actor, action,
#             resource, and timestamp. Point-in-time recovery (PITR) enabled
#             on all tables for data-durability controls.
#   - GDPR:  server_side_encryption is ENABLED on every table (AES-256 via
#             AWS-owned CMK). VoterLog stores only a SHA-256 hash of the IP —
#             no raw PII — with a TTL for automatic purge. The Right to be
#             Forgotten is fulfilled by deleting the VoterHash item.
##############################################################################

# ---------------------------------------------------------------------------
# Table 1: PollResults — vote counters (atomic ADD increments)
# ---------------------------------------------------------------------------
resource "aws_dynamodb_table" "poll_results" {
  name         = "${var.project_name}-${var.environment}-PollResults"
  billing_mode = "PAY_PER_REQUEST" # No capacity planning needed; scales automatically.
  hash_key     = "PollID"

  attribute {
    name = "PollID"
    type = "S"
  }

  # GDPR / SOC2: Encryption at rest with customer-managed CMK (CKV_AWS_119).
  # CMK usage is auditable via CloudTrail; key revocation = cryptographic erasure.
  server_side_encryption {
    enabled     = true
    kms_key_arn = aws_kms_key.main.arn
  }

  # SOC2: Point-in-time recovery for data durability and recovery objectives.
  point_in_time_recovery {
    enabled = true
  }

  tags = {
    Name         = "${var.project_name}-${var.environment}-PollResults"
    DataClass    = "Non-PII"
    GDPRRelevant = "false"
  }
}

# ---------------------------------------------------------------------------
# Table 2: VoterLog — deduplication via hashed voter fingerprint
#
# Schema:
#   PK: VoterHash  (SHA-256(rawIP + PollID + server-side salt) — NOT raw IP)
#   SK: PollID
#   TTL: ExpiresAt (Unix epoch; DynamoDB auto-deletes after this time)
#
# GDPR note: Because VoterHash is a one-way hash with a server-side salt
# (stored in Secrets Manager), it cannot be reversed to identify an individual.
# This is pseudonymisation per GDPR Article 4(5). Deleting a VoterHash item
# constitutes erasure for that voter fingerprint.
# ---------------------------------------------------------------------------
resource "aws_dynamodb_table" "voter_log" {
  name         = "${var.project_name}-${var.environment}-VoterLog"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "VoterHash"
  range_key    = "PollID"

  attribute {
    name = "VoterHash"
    type = "S"
  }

  attribute {
    name = "PollID"
    type = "S"
  }

  # TTL: items are automatically deleted after var.voter_dedup_ttl_hours.
  # This is the primary GDPR data-minimisation mechanism for this table.
  ttl {
    attribute_name = "ExpiresAt"
    enabled        = true
  }

  server_side_encryption {
    enabled     = true
    kms_key_arn = aws_kms_key.main.arn
  }

  point_in_time_recovery {
    enabled = true
  }

  tags = {
    Name            = "${var.project_name}-${var.environment}-VoterLog"
    DataClass       = "Pseudonymised"
    GDPRRelevant    = "true"
    RetentionPolicy = "${var.voter_dedup_ttl_hours}h-TTL"
  }
}

# ---------------------------------------------------------------------------
# Table 3: AuditLog — immutable SOC2 audit trail
#
# Schema:
#   PK: EventID  (UUID v4 — generated by Lambda)
#   SK: Timestamp (ISO-8601)
#   ActorID:    VoterHash or "system"
#   Action:     "VOTE_CAST" | "RESULTS_READ" | "DUPLICATE_VOTE_REJECTED"
#   ResourceID: "PollID#<id>"
#   Outcome:    "SUCCESS" | "FAILURE"
#
# This table is append-only by design. The Lambda IAM role has ONLY
# dynamodb:PutItem on this table — no update or delete permissions.
# ---------------------------------------------------------------------------
resource "aws_dynamodb_table" "audit_log" {
  name         = "${var.project_name}-${var.environment}-AuditLog"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "EventID"
  range_key    = "Timestamp"

  attribute {
    name = "EventID"
    type = "S"
  }

  attribute {
    name = "Timestamp"
    type = "S"
  }

  server_side_encryption {
    enabled     = true
    kms_key_arn = aws_kms_key.main.arn
  }

  # SOC2: PITR on the audit log ensures it cannot be silently wiped.
  point_in_time_recovery {
    enabled = true
  }

  tags = {
    Name         = "${var.project_name}-${var.environment}-AuditLog"
    DataClass    = "Audit"
    GDPRRelevant = "false"
    Immutable    = "true"
  }
}
